- hosts: all
  become: true
  tasks: 
    #  - name: delete old deployment
    #    command: kubectl delete -f /home/azureuser/gjak-demo/k8s/Deployment.yml
    #  - name: delete old service
    #    command: kubectl delete -f /home/azureuser/gjak-demo/k8s/Service.yml
     - name: create new deployment
       command: kubectl apply -f /home/azureuser/gjak-demo/k8s/Deployment.yml
     - name: create new service
       command: kubectl apply -f /home/azureuser/gjak-demo/k8s/Service.yml
